name: Update OpenAPI Specification for polar.sh

on:
  workflow_dispatch:
  schedule:
  # Daily at noon
  - cron: '0 12 * * *'

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.6.5

jobs:
  update_openapi_specification:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
      with:
        version: ${{ env.UV_VERSION }}
    - run: uv run scripts/update_openapi.py
    - uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7.0.7
      with:
        title: 'chore: Update OpenAPI Specification for polar.sh'
        token: ${{ steps.generate-token.outputs.token }}
