name: Update OpenAPI Specification for polar.sh

on:
  workflow_dispatch:
  schedule:
  # Daily at noon
  - cron: '0 12 * * *'

jobs:
  update_openapi_specification:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/create-github-app-token@v1
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v4
      with:
        version: ">=0.4.18"
    - run: uv run scripts/update_openapi.py
    - uses: peter-evans/create-pull-request@v7
      with:
        title: 'chore: Update OpenAPI Specification for polar.sh'
        token: ${{ steps.generate-token.outputs.token }}
